<table class="admin-table">
    <tr>
        <th width="20">ID</th>
        <th width="150"><?=$this->translate('sysname')?></th>
        <th><?=$this->translate('subject')?></th>
        <th width="10"><?=$this->translate('actions')?></th>
    </tr>
    <?php foreach ($this->pager->execute() as $item) { ?>
        <tr>
            <td align="center"><?php echo $item->id; ?></td>
            <td ><?php echo $this->link($item->sysname, $this->url(array('action' => 'template-edit', 'id' => $item->id))); ?></td>
            <td align="center"><?php echo $item->subject; ?></td>
            <td align="center" nowrap="nowrap">
                <?php echo $this->link('Edit', $this->url(array('action' => 'template-edit', 'id' => $item->id)),
                        array('class' => 'edit-item')); ?>
                <?php echo $this->link('Delete', $this->url(array('action' => 'template-delete', 'id' => $item->id)),
                        array('class' => 'delete-item'), 'Delete this template?'); ?>
        </td>
    </tr>
<?php } ?>
</table>
