<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Region_Model_Mapper_BaseRegion', 'doctrine');

/**
 * Region_Model_Mapper_BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Region_Model_Mapper_City
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Region_Model_Mapper_BaseRegion extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('region_regions');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Region_Model_Mapper_City', array(
             'local' => 'id',
             'foreign' => 'region_id'));
    }
}