<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Region_Model_Mapper_BaseCity', 'doctrine');

/**
 * Region_Model_Mapper_BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $region_id
 * @property string $delivery_type
 * @property Region_Model_Mapper_Region $Region
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Region_Model_Mapper_BaseCity extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('region_cities');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '11',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('region_id', 'integer', 11, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '11',
             ));
        $this->hasColumn('delivery_type', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Region_Model_Mapper_Region as Region', array(
             'local' => 'region_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}