<?php

/**
 * Banner_Model_Mapper_BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property enum $type
 * @property string $link
 * @property string $src
 * @property string $sysmap_id
 * @property string $text
 * @property int $flash_width
 * @property int $flash_height
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banner_Model_Mapper_BaseBanner extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('banner');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'text',
              1 => 'image',
              2 => 'flash',
             ),
             'default' => 'text',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('src', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('sysmap_id', 'string', 35, array(
             'type' => 'string',
             'length' => '35',
             ));
        $this->hasColumn('text', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('flash_width', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('flash_height', 'int', null, array(
             'type' => 'int',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}